import { DragState } from "./dragDispatcher";
import { InterfaceState } from "./interfaceDispatcher";
import { Node } from "./nodeDispatcher";

const VIEWPORT_GAP = 160;

export interface NodeState {
  nodes: Node[];
  selectedNodeIds: (string | number)[] | null;
}

export const nodeInitialState: NodeState = {
  nodes: [
    {
      id: "viewport-1440",
      type: "frame",
      isViewport: true,
      viewportName: "Desktop",
      viewportWidth: 1440,
      style: {
        width: "1440px",
        height: "1000px",
        position: "absolute",
        backgroundColor: "white",
        boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        left: "0px",
        top: "0px",
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
      },
      inViewport: false,
      parentId: null,
      position: { x: 100, y: 100 },
    },
    {
      id: "viewport-768",
      type: "frame",
      isViewport: true,
      viewportWidth: 768,
      style: {
        width: "768px",
        height: "1000px",
        position: "absolute",
        backgroundColor: "white",
        boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        left: `${1440 + VIEWPORT_GAP}px`,
        top: "0px",
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
      },
      inViewport: false,
      viewportName: "Tablet",
      parentId: null,
      position: { x: 100 + 1440 + VIEWPORT_GAP, y: 100 },
    },
    {
      id: "viewport-375",
      type: "frame",
      isViewport: true,
      viewportWidth: 375,
      style: {
        width: "375px",
        height: "1000px",
        position: "absolute",
        backgroundColor: "white",
        boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        left: `${1440 + VIEWPORT_GAP + 768 + VIEWPORT_GAP}px`,
        top: "0px",
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
      },
      inViewport: false,
      viewportName: "Mobile",
      parentId: null,
      position: { x: 100 + 1440 + VIEWPORT_GAP + 768 + VIEWPORT_GAP, y: 100 },
    },
    {
      id: "ez4VLzf45AS_tp7IoalXo",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#ef1515",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      isDynamic: true,
      parentId: "viewport-1440",
      sharedId: "4f82Xkpp_pzkVi4mvj5lm",
    },
    {
      id: "gmzB5qAqsN86mljbgWz5D",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "gray",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-1440",
      sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    },
    {
      id: "0UJKRiqHTcy5MhpWEl1MX",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#ef1515",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      isDynamic: true,
      parentId: "viewport-768",
      sharedId: "4f82Xkpp_pzkVi4mvj5lm",
    },
    {
      id: "A7gGQS30zoHnZCRJJuPlm",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "gray",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-768",
      sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    },
    {
      id: "oGkgT6xyRRYcTjpO8JQXK",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#ef1515",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      isDynamic: true,
      parentId: "viewport-375",
      sharedId: "4f82Xkpp_pzkVi4mvj5lm",
    },
    {
      id: "VEgCDoIoYsoxaBebzYXuh",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "gray",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-375",
      sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    },
  ],
  selectedNodeIds: null,
};

export const dragInitialState: DragState = {
  isDragging: false,
  draggedItem: null,
  draggedNode: null,
  dropInfo: {
    targetId: null,
    position: null,
  },
  selectedIds: [],
  originalParentId: null,
  placeholderId: null,
  originalIndex: null,
  lineIndicator: {
    show: false,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
  },
  dragSource: null,
  snapGuides: [],
  styleHelper: {
    show: false,
    type: null,
    position: { x: 0, y: 0 },
    value: undefined,
    dimensions: undefined,
  },
  dynamicModeNodeId: null,
  contextMenu: null,
  gripHandleDirection: null,
  hoverNodeId: null,
  dragPositions: {
    x: 0,
    y: 0,
  },
  isOverCanvas: false,
  recordingSessionId: null,
  originalWidthHeight: { width: 0, height: 0, isFillMode: false },
  isSelectionBoxActive: false,
  tempSelectedIds: [],
  nodeDimensions: {},
  duplicatedFromAlt: false,
  placeholderInfo: null,
  lastMouseX: 0,
  lastMouseY: 0,
  dynamicState: "normal",
  connectionTypeModal: {
    show: false,
    position: { x: 0, y: 0 },
    sourceId: null,
    targetId: null,
  },
};

export const interfaceInitialState: InterfaceState = {
  isInsertOpen: false,
  isLayersOpen: false,
  isCmsOpen: false,
  isPreviewOpen: false,
  isPagesOpen: false,
  isComponentsOpen: false,
  isTyping: false,
};
