import { Node } from "./nodeDispatcher";

const VIEWPORT_GAP = 160;

export interface NodeState {
  nodes: Node[];
  selectedNodeIds: (string | number)[] | null;
}

export const nodeInitialState: NodeState = {
  nodes: [
    {
      id: "viewport-1440",
      type: "frame",
      isViewport: true,
      sharedId: "desfaultSharedIdview8",
      viewportName: "Desktop",
      viewportWidth: 1440,
      style: {
        width: "1440px",
        height: "1000px",
        position: "absolute",
        backgroundColor: "white",
        boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        left: "0px",
        top: "0px",
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
      },
      inViewport: false,
      parentId: null,
      position: { x: 100, y: 100 },
    },
    {
      id: "viewport-768",
      type: "frame",
      isViewport: true,
      sharedId: "desfaultSharedIdview8",
      viewportWidth: 768,
      style: {
        width: "768px",
        height: "1000px",
        position: "absolute",
        backgroundColor: "white",
        boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        left: `${1440 + VIEWPORT_GAP}px`,
        top: "0px",
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
      },
      inViewport: false,
      viewportName: "Tablet",
      parentId: null,
      position: { x: 100 + 1440 + VIEWPORT_GAP, y: 100 },
    },
    {
      id: "viewport-375",
      type: "frame",
      isViewport: true,
      sharedId: "desfaultSharedIdview8",
      viewportWidth: 375,
      style: {
        width: "375px",
        height: "1000px",
        position: "absolute",
        backgroundColor: "white",
        boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        left: `${1440 + VIEWPORT_GAP + 768 + VIEWPORT_GAP}px`,
        top: "0px",
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
      },
      inViewport: false,
      viewportName: "Mobile",
      parentId: null,
      position: { x: 100 + 1440 + VIEWPORT_GAP + 768 + VIEWPORT_GAP, y: 100 },
    },
    // First frame (red)
    {
      id: "ez4VLzf45AS_tp7IoalXo",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#ef1515",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      isDynamic: true,
      parentId: "viewport-1440",
      sharedId: "4f82Xkpp_pzkVi4mvj5lm",
    },
    // Second frame (gray)
    {
      id: "gmzB5qAqsN86mljbgWz5D",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "gray",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-1440",
      sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    },
    // Third frame with image child (blue)
    {
      id: "ThirdFrame_1440",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#1515ef",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-1440",
      sharedId: "ThirdFrameSharedId",
    },
    // Image inside third frame
    {
      id: "ThirdFrameImage_1440",
      type: "image",
      style: {
        width: "100px",
        height: "50px",
        position: "relative",
        src: "https://batiment.imag.fr/img/imag.png",
      },
      inViewport: true,
      parentId: "ThirdFrame_1440",
      sharedId: "ThirdFrameImageSharedId",
    },
    // Fourth frame with nested frame and image (green)
    {
      id: "FourthFrame_1440",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#15ef15",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-1440",
      sharedId: "FourthFrameSharedId",
    },
    // Nested frame inside fourth frame
    {
      id: "NestedFrame_1440",
      type: "frame",
      style: {
        width: "100px",
        height: "100px",
        position: "relative",
        backgroundColor: "#008000",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "FourthFrame_1440",
      sharedId: "NestedFrameSharedId",
    },
    // Image inside nested frame
    {
      id: "NestedFrameImage_1440",
      type: "image",
      style: {
        width: "80px",
        height: "40px",
        position: "relative",
        src: "https://batiment.imag.fr/img/imag.png",
      },
      inViewport: true,
      parentId: "NestedFrame_1440",
      sharedId: "NestedFrameImageSharedId",
    },
    // Direct image child of viewport

    // Direct text child of viewport

    // Tablet viewport (768) - same elements
    {
      id: "0UJKRiqHTcy5MhpWEl1MX",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#ef1515",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      isDynamic: true,
      parentId: "viewport-768",
      sharedId: "4f82Xkpp_pzkVi4mvj5lm",
    },
    {
      id: "A7gGQS30zoHnZCRJJuPlm",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "gray",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-768",
      sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    },
    // Third frame with image child (blue) - tablet
    {
      id: "ThirdFrame_768",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#1515ef",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-768",
      sharedId: "ThirdFrameSharedId",
    },
    // Image inside third frame - tablet
    {
      id: "ThirdFrameImage_768",
      type: "image",
      style: {
        width: "100px",
        height: "50px",
        position: "relative",
        src: "https://batiment.imag.fr/img/imag.png",
      },
      inViewport: true,
      parentId: "ThirdFrame_768",
      sharedId: "ThirdFrameImageSharedId",
    },
    // Fourth frame with nested frame and image (green) - tablet
    {
      id: "FourthFrame_768",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#15ef15",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-768",
      sharedId: "FourthFrameSharedId",
    },
    // Nested frame inside fourth frame - tablet
    {
      id: "NestedFrame_768",
      type: "frame",
      style: {
        width: "100px",
        height: "100px",
        position: "relative",
        backgroundColor: "#008000",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "FourthFrame_768",
      sharedId: "NestedFrameSharedId",
    },
    // Image inside nested frame - tablet
    {
      id: "NestedFrameImage_768",
      type: "image",
      style: {
        width: "80px",
        height: "40px",
        position: "relative",
        src: "https://batiment.imag.fr/img/imag.png",
      },
      inViewport: true,
      parentId: "NestedFrame_768",
      sharedId: "NestedFrameImageSharedId",
    },
    // Direct image child of viewport - tablet
    {
      id: "DirectImage_768",
      type: "image",
      style: {
        width: "200px",
        height: "100px",
        position: "relative",
        src: "https://batiment.imag.fr/img/imag.png",
      },
      inViewport: true,
      parentId: "viewport-768",
      sharedId: "DirectImageSharedId",
    },
    // Direct text child of viewport - tablet
    {
      id: "DirectText_768",
      type: "text",
      style: {
        width: "auto",
        height: "auto",
        position: "relative",
        text: "Hello Tablet Viewport",
        fontSize: "20px",
        color: "#333333",
      },
      inViewport: true,
      parentId: "viewport-768",
      sharedId: "DirectTextSharedId",
    },

    // Mobile viewport (375) - same elements
    {
      id: "oGkgT6xyRRYcTjpO8JQXK",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#ef1515",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      isDynamic: true,
      parentId: "viewport-375",
      sharedId: "4f82Xkpp_pzkVi4mvj5lm",
    },
    {
      id: "VEgCDoIoYsoxaBebzYXuh",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "gray",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-375",
      sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    },
    // Third frame with image child (blue) - mobile
    {
      id: "ThirdFrame_375",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#1515ef",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-375",
      sharedId: "ThirdFrameSharedId",
    },
    // Image inside third frame - mobile
    {
      id: "ThirdFrameImage_375",
      type: "image",
      style: {
        width: "100px",
        height: "50px",
        position: "relative",
        src: "https://batiment.imag.fr/img/imag.png",
      },
      inViewport: true,
      parentId: "ThirdFrame_375",
      sharedId: "ThirdFrameImageSharedId",
    },
    // Fourth frame with nested frame and image (green) - mobile
    {
      id: "FourthFrame_375",
      type: "frame",
      style: {
        width: "150px",
        height: "150px",
        position: "relative",
        backgroundColor: "#15ef15",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "viewport-375",
      sharedId: "FourthFrameSharedId",
    },
    // Nested frame inside fourth frame - mobile
    {
      id: "NestedFrame_375",
      type: "frame",
      style: {
        width: "100px",
        height: "100px",
        position: "relative",
        backgroundColor: "#008000",
        zIndex: "",
        transform: "",
        left: "",
        top: "",
      },
      inViewport: true,
      parentId: "NestedFrame_375",
      sharedId: "NestedFrameSharedId",
    },
    // Image inside nested frame - mobile
    {
      id: "NestedFrameImage_375",
      type: "image",
      style: {
        width: "80px",
        height: "40px",
        position: "relative",
        src: "https://batiment.imag.fr/img/imag.png",
      },
      inViewport: true,
      parentId: "NestedFrame_375",
      sharedId: "NestedFrameImageSharedId",
    },
    // Direct image child of viewport - mobile
    {
      id: "DirectImage_375",
      type: "image",
      style: {
        width: "150px",
        height: "75px",
        position: "relative",
        src: "https://batiment.imag.fr/img/imag.png",
      },
      inViewport: true,
      parentId: "viewport-375",
      sharedId: "DirectImageSharedId",
    },
  ],
  selectedNodeIds: null,
};
