export const nodes = [
  {
    id: "viewport-1440",
    type: "frame",
    isViewport: true,
    viewportName: "Desktop",
    viewportWidth: 1440,
    style: {
      width: "1440px",
      height: "1000px",
      position: "absolute",
      backgroundColor: "white",
      boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      left: "0px",
      top: "0px",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    inViewport: false,
    parentId: null,
    position: {
      x: 100,
      y: 100,
    },
  },
  {
    id: "viewport-768",
    type: "frame",
    isViewport: true,
    viewportWidth: 768,
    style: {
      width: "768px",
      height: "1000px",
      position: "absolute",
      backgroundColor: "white",
      boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      left: "1600px",
      top: "0px",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    inViewport: false,
    viewportName: "Tablet",
    parentId: null,
    position: {
      x: 1700,
      y: 100,
    },
  },
  {
    id: "viewport-375",
    type: "frame",
    isViewport: true,
    viewportWidth: 375,
    style: {
      width: "375px",
      height: "1000px",
      position: "absolute",
      backgroundColor: "white",
      boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      left: "2528px",
      top: "0px",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    inViewport: false,
    viewportName: "Mobile",
    parentId: null,
    position: {
      x: 2628,
      y: 100,
    },
  },
  {
    id: "0WJMXL7bGBNR670TZyxCD",
    type: "frame",
    style: {
      width: "661.1687432328947px",
      height: "410.9384160231327px",
      position: "relative",
      backgroundColor: "gray",
      zIndex: "",
      transform: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    inViewport: true,
    parentId: "viewport-1440",
    sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
      gap: true,
    },
  },
  {
    id: "I-uG-zFiBsofyRX5hPtns",
    type: "text",
    style: {
      width: "150px",
      height: "150px",
      position: "relative",
      flex: "0 0 auto",
      zIndex: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "0px",
      color: "black",
      text: '<p class="text-inherit"><span style="color: rgb(229, 84, 84); font-size: 39.1823px"><strong>sdfsdfs</strong></span></p>',
    },
    inViewport: true,
    parentId: "0WJMXL7bGBNR670TZyxCD",
    sharedId: "I5qufpzzFMdETPgUflIMv",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
    },
  },
  {
    id: "QOflxRQfiRyabk2W7Sowj",
    type: "text",
    style: {
      width: "150px",
      height: "150px",
      position: "relative",
      flex: "0 0 auto",
      zIndex: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "0px",
      color: "black",
      text: '<p class="text-inherit"><span style="color: rgb(229, 84, 84); font-size: 39.1823px"><strong>sdfsdfs</strong></span></p>',
    },
    inViewport: true,
    parentId: "0WJMXL7bGBNR670TZyxCD",
    sharedId: "qpXkbocYDG8EVUOh7Xjbh",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
      text: true,
    },
  },
  {
    id: "lr7CmCnSIxXt382WgxTsy",
    type: "frame",
    style: {
      width: "451.07901810337637px",
      height: "445.0858371680122px",
      position: "relative",
      backgroundColor: "gray",
      zIndex: "",
      transform: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "56px",
    },
    inViewport: true,
    parentId: "viewport-768",
    sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
      gap: true,
    },
  },
  {
    id: "_7p5Z8UqnIr3pLzSaUP52",
    type: "text",
    style: {
      width: "150px",
      height: "150px",
      position: "relative",
      flex: "0 0 auto",
      zIndex: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "0px",
      color: "black",
      text: '<p class="text-inherit"><span style="color: rgb(229, 84, 84); font-size: 39.1823px"><strong>sdfsdfs</strong></span></p>',
    },
    inViewport: true,
    parentId: "lr7CmCnSIxXt382WgxTsy",
    sharedId: "I5qufpzzFMdETPgUflIMv",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
    },
  },
  {
    id: "xSE66z4d5pjOsWWoaYi1O",
    type: "text",
    style: {
      width: "150px",
      height: "150px",
      position: "relative",
      flex: "0 0 auto",
      zIndex: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "0px",
      color: "black",
      text: '<p class="text-inherit"><span style="color: #53d1d0; font-size: 39.1823px"><strong>sdfsdfs</strong></span></p>',
    },
    inViewport: true,
    parentId: "lr7CmCnSIxXt382WgxTsy",
    sharedId: "qpXkbocYDG8EVUOh7Xjbh",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
      text: true,
    },
  },
  {
    id: "luliarmNVrAtRAqv0PWHZ",
    type: "frame",
    style: {
      width: "380px",
      height: "194.479px",
      position: "relative",
      backgroundColor: "gray",
      zIndex: "",
      transform: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    inViewport: true,
    parentId: "viewport-375",
    sharedId: "CqU3kVaMaLinQIEr3Bv1a",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
      gap: true,
    },
  },
  {
    id: "ZMz6_HBKeu7NY3IRn5D0J",
    type: "text",
    style: {
      width: "150px",
      height: "150px",
      position: "relative",
      flex: "0 0 auto",
      zIndex: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "0px",
      color: "black",
      text: '<p class="text-inherit"><span style="color: rgb(229, 84, 84); font-size: 39.1823px"><strong>sdfsdfs</strong></span></p>',
    },
    inViewport: true,
    parentId: "luliarmNVrAtRAqv0PWHZ",
    sharedId: "I5qufpzzFMdETPgUflIMv",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
    },
  },
  {
    id: "7xfdKAOcphBH6aF-BtAY2",
    type: "text",
    style: {
      width: "150px",
      height: "150px",
      position: "relative",
      flex: "0 0 auto",
      zIndex: "",
      left: "",
      top: "",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "0px",
      color: "black",
      text: '<p class="text-inherit"><span style="color: rgb(229, 84, 84); font-size: 39.1823px"><strong>sdfsdfs</strong></span></p>',
    },
    inViewport: true,
    parentId: "luliarmNVrAtRAqv0PWHZ",
    sharedId: "qpXkbocYDG8EVUOh7Xjbh",
    independentStyles: {
      left: true,
      top: true,
      position: true,
      zIndex: true,
      width: true,
      height: true,
      text: true,
    },
  },
];
